services:
    php:
        build: .
        ports:
            - "9000:9000"
        command: php -S localhost:9000
        working_dir: /src/public
        restart: always
        volumes:
          - .:/app
        depends_on:
          - mysql
    
    mysql:
        image: mysql:8.0
        ports:
            - "3308:3306"
        restart: always
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: atelier
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
          - ./mysql:/var/lib/mysql
