services:
    php:
        build: .
        ports:
            - "8081:8081"
        command: php -S 0.0.0.0:8081 
        working_dir: /app/public
        restart: always
        volumes:
          - .:/app
        depends_on:
          - mysql
    
    mysql:
        image: mysql:8.0
        ports:
            - "3308:3306"
        restart: always
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: atelier
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
          - ./mysql:/var/lib/mysql
